config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as:'rails_admin'
  devise_for :users

  root to: 'movies#index', constraints: -> (r) { r.env["warden"].authenticate? }, as: :authenticated_root
  root to: 'pages#landing'
  
  get "dashboard", to: "pages#dashboard", as: "dashboard"

  resources :movies, only: [:index, :show]

  resources :user_movies, only: [:update] do
    collection do
      post "create_watch", to: "user_movies#create_watch", as: "watch"
      post "create_catalogue", to: "user_movies#create_catalogue", as: "catalogue"
    end
  end

  resources :profiles, only: [ :show ]
  resources :movie_tags, only: [:create]

  # Old routes...

  # get 'movie_tags/create'
  # get 'user_movies/create_catalog'
  # get 'user_movies/create_watch'
  # get 'user_movies/update'
  # get 'movies/index'
  # get "/movies/:id", to: "movies#show", as:"movies_show"
  # get 'pages/dashboard'
  # get 'pages/catalogue'
  # get 'pages/watchlist'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :friendships,
      class_name: "User",
      join_table:  :friendships,
      foreign_key: :user_id,
      association_foreign_key: :friend_user_id
  has_many :user_movies, dependent: :destroy
  has_many :movies, through: :user_movies
  has_many :movie_tags, dependent: :destroy
  has_many :tags, through: :movie_tags
  has_many :reviews
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  def index
    @movie_tag = MovieTag.new
    @tags = Tag.all
    @genres = Genre.all
    my_movies
    filter_movies
  end


  def show
    @tags = Tag.all
    @movie = Movie.find(params[:id])
    @movie_tag = MovieTag.new
    reviews
    movie_availability

    respond_to do |format|
      format.html
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def movie_availability
    require "open-uri"
    require "nokogiri"

    url = "https://www.finder.com/amazon-prime-movies"

    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)
    movie_title = @movie.title
    @availability = false

    html_doc.search('tr>td:first-child').each do |element|
      if movie_title == element.text.strip
        @availability = true
        break
      end
    end
  end

  private

  def reviews
    @reviews = @movie.reviews
    @users_with_reviews = @reviews.pluck(:user_id)
  end

  def filter_movies
    if params[:clicked_tag].present? || params[:clicked_genre].present?
      filter_movies_by_selected_tags
    end
  end

  def filter_movies_by_selected_tags
    @my_movies = @my_movies.includes(:tags, :genres).select do |movie|
      movies_tags = movie.tags.pluck(:id)
      movies_genres = movie.genres.pluck(:id)
      clicked_tag_ids = params[:clicked_tag]&.keys&.map(&:to_i)
      clicked_genre_ids = params[:clicked_genre]&.keys&.map(&:to_i)

      if clicked_tag_ids && clicked_genre_ids
        clicked_tag_ids.all? { |tag_id| movies_tags.include?(tag_id) } &&
        clicked_genre_ids.all? { |genre_id| movies_genres.include?(genre_id) }
      elsif clicked_genre_ids.present?
        clicked_genre_ids.all? { |genre_id| movies_genres.include?(genre_id) }
      else
        clicked_tag_ids.all? { |tag_id| movies_tags.include?(tag_id) }
      end
    end
  end
end

app/views/movies/_movie_details.html.erb
<div class="show-container">
  <div class="movie-box">
    <iframe src='https://www.youtube.com/embed/<%= @movie.trailer%>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
  </div>
  <div class="movie-title">
    <h1><%= movie.title.upcase %><small> <%=movie.year %></small></h1>
    <div class="watchlist-button">
      <%= simple_form_for movie, :url => watch_user_movies_path, method: :post, html: { onsubmit: "watchListButton(event, this)"} do |t| %>
      <%= t.input :movie_id, as: :hidden, :input_html => { value: movie.id } %>
      <%= t.submit "Add to Watchlist", class: "watchlist-btn btn-navbar", id: "watch"%>
    <% end %>
    <div class="movie-box-buttons">
      <%= link_to "https://www.netflix.com", class: "availability-icon-netflix" do %>
        <%= image_tag url="https://res.cloudinary.com/chimeraggeddon/image/upload/v1528468187/netflix-logo-png-2616.png", height: 50 %>
      <% end %>
      <%= link_to "https://www.primevideo.com", class: "availability-icon-amazon #{@availability ? 'available' : 'unavailable'}" do %>
        <%= image_tag url="https://res.cloudinary.com/chimeraggeddon/image/upload/v1528468175/kisspng-amazon-com-gift-card-createspace-customer-service-amazon-icon-amazon-icon-5ab1b9d837e444.3509969015215968882289.png", height:60 %>
      <% end %>
    </div>
  </div>
  </div>
  <div class="movie-description"><p>
    <%= movie.plot %>
  </p>
  </div>

  <div class="infobox">
    <h4 style="text-align: center; font-weight:bolder; padding-bottom:20px; color:black;">Click tags to add to catalog</h4>
    <div class="add-tags">
      <% @tags.uniq.each do |tag| %>
        <%# f.label tag.name %>
        <%# check_box_tag "tag_ids[#{tag.id}]", tag.id,false, :name => "tag_ids[]" %>
        <%= link_to(
          tag.name,
          movie_tags_path(movie_id: movie.id, tag_id: tag.id),
          remote: true, method: :post, class: "add-tags-btn add-tag-#{tag.id} film2-genre"
        )%>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/_movie_list.html.erb
<div id="movies-index" class="flex-movie">
  <% @my_movies.each do |movie|%>

      <div class="movie-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= movie.poster? ? image_path(movie.poster, height: 300, width: 400, crop: :fill) : 'http://placeholder.it' ; %>');">
      <%= link_to "", movie_path(movie), class: "card-link", remote: true %>
    </div>
  <% end %>
</div>

app/views/movies/_search_header.html.erb
<%= form_tag movies_path, remote: true, method: :get, id: "form" do %>
  <div class="header">
    <div class="genre-box">
      <div class="genres row" id="genre-row">
        <% (@genres).limit(12).each do |filter|%>
          <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 genre-bg">
            <div class = "tags text-center">
              <button class="btn-filmy2 film2-genre list-inline"><%= filter.name %><%= check_box_tag "clicked_#{filter.class.to_s.downcase}[#{filter.id}]" %></button>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="tag-box">
      <div class=" row" id="tags-row">
        <% (@tags).limit(12).each do |filter|%>
          <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 genre-bg">
            <div class = "tags text-center">
              <button class="btn-filmy2 film2-tag list-inline"><%= filter.name %><%= check_box_tag "clicked_#{filter.class.to_s.downcase}[#{filter.id}]" %></button>
            </div>
          </div>
        <% end %>
        <%= submit_tag "filter", id: "filter-movies", style: "display: none" %>
      </div>
    </div>
    </div>
<% end %>

app/views/movies/index.html.erb
<div class="main-container-index">
  <div class="movie-poster-mozaic">
    <%= render 'movies/search_header' %>
    <div class="flex-mozaic">
      <%= render "movie_list" %>
    </div>
  </div>
  <div id="sidebar-container" class="sidebar-container">
    <div id="sidebar-wrapper" class="movie-poster-sidebar" onclick="sidebarClick(event, this)">
    </div>
     <div id="movie-sidebar" class="movie-sidebar" ></div>
  </div>
</div>

app/views/movies/index.js.erb
document.getElementById("movies-index").innerHTML = "<%= j(render 'movie_list') %>";

app/views/movies/show.html.erb
<div class="show-wrapper">
  <div class="movie-show-container">
    <div class="movie-description-section row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="movie-box">
          <iframe src='https://www.youtube.com/embed/<%= @movie.trailer%>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
        </div>
        <div class="movie-title">
        </div>
        <h1><%= @movie.title.upcase %><small> <%= @movie.year %></small></h1>
        <hr>
        <div class="movie-description"><p>
          <%= @movie.plot %>
        </p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="director">
          <h3>DIRECTOR</h3>
          <p><%= @movie.director %></p>
        </div>
        <div class="actor">
          <h3>ACTORS</h3>
          <p>Lorem Ipsum</p>
        </div>
        <div class="genre">
          <h3>GENRE</h3>
          <p>Lorem Ipsum</p>
        </div>
        <div class="lenght">
          <h3>LENGTH</h3>
          <% hour = @movie.runtime.to_i/60 %>
          <% minutes = @movie.runtime.to_i%60 %>
          <p><%= hour %>h <%= minutes %>m</p>
        </div>
        <div class="button-link-watch">
          <ul class="list-inline">
            <li class="btn-sites">Netflix</li>
            <li class="btn-sites">Hulu</li>
            <li class="btn-sites">Amazon</li>
          </ul>
        </div>

        <div class="add-to-catalog">
      <%= simple_form_for @movie, :url => catalogue_user_movies_path, method: :post do |t| %>
        <%= t.input :@movie_id, as: :hidden, :input_html => { value: @movie.id } %>
         <%= t.submit "Add to Catalogue", class: "btn-filmy"%>
      <% end %>
    </div>

        <!-- <div class="btn" id="add-catalogue">Add to Catalogue</div> -->

      </div>
    </div>
    <div class="blue-bar-reviews">
    <h2>
      USERS' REVIEWS FOR <%= @movie.title.upcase %>
    </h2>
    </div>
    <div class="review-cards-container">
      <div class="movie-review-section row">

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 card-review" >
          <% @reviews.limit(3).each do |review| %>
          <div class="card-review-body">
            <div class="card-review-avatar">
              <% review_user_id = review.user_id %>
              <% review_user = User.find_by_id(review_user_id) %>
              <%= image_tag(review_user.avatar, :class => "review_avatar") %>
            </div>
            <h3 class="card-review-title"><%= review_user.username %>s Review</h3>
            <p class="card-review-content"><%= review.text %></p>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.js.erb
document.getElementById("movie-sidebar").innerHTML = '<%= j render "movie_details", movie: @movie %>';
document.getElementById("movie-sidebar").classList.toggle("open-sidebar")
document.getElementById("sidebar-wrapper").classList.toggle("open-bg-sidebar")
document.getElementById("sidebar-container").classList.toggle("open-bg-sidebar")