config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as:'rails_admin'
  devise_for :users

  root to: 'movies#index', constraints: -> (r) { r.env["warden"].authenticate? }, as: :authenticated_root
  root to: 'pages#landing'
  
  get "dashboard", to: "pages#dashboard", as: "dashboard"

  resources :movies, only: [:index, :show]

  resources :user_movies, only: [:update] do
    collection do
      post "create_watch", to: "user_movies#create_watch", as: "watch"
      post "create_catalogue", to: "user_movies#create_catalogue", as: "catalogue"
    end
  end

  resources :profiles, only: [ :show ]
  resources :movie_tags, only: [:create]

  # Old routes...

  # get 'movie_tags/create'
  # get 'user_movies/create_catalog'
  # get 'user_movies/create_watch'
  # get 'user_movies/update'
  # get 'movies/index'
  # get "/movies/:id", to: "movies#show", as:"movies_show"
  # get 'pages/dashboard'
  # get 'pages/catalogue'
  # get 'pages/watchlist'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend_user, class_name: 'User'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :genres
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :user_movies, dependent: :destroy
  has_many :users, through: :user_movies
  has_many :movie_actors
  has_many :actors, through: :movie_actors
  has_many :movie_genres
  has_many :genres, through: :movie_genres
  # has_many :movie_genres, through: :genres
  # has_many :tags
  # has_many :movie_tags, through: :tags

  has_many :movie_tags, dependent: :destroy
  has_many :tags, through: :movie_tags
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :movie
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :movie_tags
  has_many :movies, through: :movie_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :friendships,
      class_name: "User",
      join_table:  :friendships,
      foreign_key: :user_id,
      association_foreign_key: :friend_user_id
  has_many :user_movies, dependent: :destroy
  has_many :movies, through: :user_movies
  has_many :movie_tags, dependent: :destroy
  has_many :tags, through: :movie_tags
  has_many :reviews
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  def self.find_or_create(current_user_id, movie_id)
    user_movie = self.where(user_id: current_user_id, movie_id: movie_id)

    if user_movie.empty?
      user_movie = self.create(user_id: current_user_id, movie_id: movie_id)
    else
      user_movie
    end

  end
end

app/controllers/dashboard_controller.rb
class DashboardsController < ApplicationController
  def edit
  end

  def update
  end

  def destroy
  end

  def friend
  end
end

app/controllers/home_controller.rb
class HomesController < ApplicationController
  def show
  end

  def index
  end

  def update_tag
  end

  def update_watchlist
  end
end

app/controllers/movie_tags_controller.rb
class MovieTagsController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    @tag = Tag.find(params[:tag_id])

    user_movie = UserMovie.find_or_create(current_user.id, @movie.id)
    user_movie.update(watched: true)

    MovieTag.create!(
      user: current_user,
      movie: @movie,
      tag: @tag
    )
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  def index
    @movie_tag = MovieTag.new
    @tags = Tag.all
    @genres = Genre.all
    my_movies
    filter_movies
  end


  def show
    @tags = Tag.all
    @movie = Movie.find(params[:id])
    @movie_tag = MovieTag.new
    reviews
    movie_availability

    respond_to do |format|
      format.html
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def movie_availability
    require "open-uri"
    require "nokogiri"

    url = "https://www.finder.com/amazon-prime-movies"

    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)
    movie_title = @movie.title
    @availability = false

    html_doc.search('tr>td:first-child').each do |element|
      if movie_title == element.text.strip
        @availability = true
        break
      end
    end
  end

  private

  def reviews
    @reviews = @movie.reviews
    @users_with_reviews = @reviews.pluck(:user_id)
  end

  def filter_movies
    if params[:clicked_tag].present? || params[:clicked_genre].present?
      filter_movies_by_selected_tags
    end
  end

  def filter_movies_by_selected_tags
    @my_movies = @my_movies.includes(:tags, :genres).select do |movie|
      movies_tags = movie.tags.pluck(:id)
      movies_genres = movie.genres.pluck(:id)
      clicked_tag_ids = params[:clicked_tag]&.keys&.map(&:to_i)
      clicked_genre_ids = params[:clicked_genre]&.keys&.map(&:to_i)

      if clicked_tag_ids && clicked_genre_ids
        clicked_tag_ids.all? { |tag_id| movies_tags.include?(tag_id) } &&
        clicked_genre_ids.all? { |genre_id| movies_genres.include?(genre_id) }
      elsif clicked_genre_ids.present?
        clicked_genre_ids.all? { |genre_id| movies_genres.include?(genre_id) }
      else
        clicked_tag_ids.all? { |tag_id| movies_tags.include?(tag_id) }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping, :resource_class
  skip_before_action :authenticate_user!

  def landing
    @movie = Movie.all
    @user = User.all
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  #------------Dashboard Methods-------------#
  def dashboard

    search
    my_profile
    @movie_tag = MovieTag.new
    @user_movies = UserMovie.all
  end

  def catalogue
    respond_to do |format|
      format.html
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end

  end
  def watchlist
    respond_to do |format|
      format.html
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end

  end











  def search
    if params[:query].present?
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end

  def my_profile
    @user = current_user
  end

  def friends_dashboard
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def create
  end

  def show
    @friend = User.find_by_id(params[:id])
    @movies = @friend.movies
    top_tags
  end

  def destroy
  end

  def top_tags
    freq = @friend.tags.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    @top_tags = freq.sort_by{|k,v| -v}[0..2].flatten
    @top_tags.delete_at(1)
    @top_tags.delete_at(2)
    @top_tags.delete_at(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <title><%= meta_title %></title>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Questrial|Pacifico" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="fixed-navbar-adjust" style="margin-top:70px;">
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/_my_film_index.html.erb
<div id="movies-index" class="flex-movie">
  <% current_user.user_movies.select { |m| m.watched }.each do |user_movie|%>
      <div class="movie-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= user_movie.movie.poster? ? image_path(user_movie.movie.poster, height: 300, width: 400, crop: :fill) : 'http://placeholder.it' ; %>');">
                <%= link_to "", movie_path(user_movie.movie), class: "card-link" %>
    </div>
  <% end %>
</div>

app/views/pages/_my_watchlist_index.html.erb
<div id="movies-index" class="flex-movie">
  <% current_user.user_movies.reject { |m| m.watched }.each do |user_movie|%>

      <div class="movie-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= user_movie.movie.poster? ? image_path(user_movie.movie.poster, height: 300, width: 400, crop: :fill) : 'http://placeholder.it' ; %>');">
        <%= link_to "", movie_path(user_movie.movie), class: "card-link" %>


    </div>
  <% end %>
</div>

app/views/pages/catalogue.js.erb
document.getElementById("bottom-section").innerHTML = '<%= j render "my_film_index"%>';

app/views/pages/dashboard.html.erb
<div class="wrapper">
	<div class="dashboard-main-container">
		<div class="banner-dashboard">
			<div class="current-user-card">
				<% if current_user.avatar? %>
				<%= image_tag(@user.avatar, :style => "width: 300px; border-radius: 50px;", :class => "card-user-pic") %>
				<% else %>
				<%= image_tag(url="https://vignette.wikia.nocookie.net/tumblr-survivor-athena/images/7/7a/Blank_Avatar.png/revision/latest/scale-to-width-down/477?cb=20161204161729", :style => "width: 300px; border-radius: 50px;", :class => "card-user-pic") %>
				<% end %>
				<div class="card-details">
					<% if current_user.username? %>
					<h2><%= @user.username.upcase %></h2>
					<% else %>
					<h2></h2>
					<% end %>
					<h3>Tags Added: 0 </h3>
				</div>
			</div>
		</div>
		<div class="friend-chat-container">
			<div class="friends-zone">
        <br>
        <hr>

				<h1 id="">YOUR FRIENDS</h1>
        <br>



				<div class="my-friends">
					<% current_user.friendships.each do |friend| %>
					<div class="">
						<%= link_to( profile_path(friend.id), html_options = {} ) do  %>
						<div class="friend-card-container">
							<div class="friend-card-body">
								<%= image_tag(friend.avatar, :class => "friend-card-photo") %>
								<div class="friend-card-footer">
									<p><%= friend.username.upcase %></p>
								</div>
							</div>
						</div>
						<% end %>
					</div>
					<% end %>
				</div>
			</div>
      <script>
        const switchTab = (event, contain, tab) => {
          const activeContain = document.getElementById(contain);
          const activeTab = document.getElementById(tab);
          if (activeContain.classList.contains('display-none')) {
            document.getElementById('my-catalogue').classList.add("display-none");
            document.getElementById('my-watchlist').classList.add("display-none");
            document.getElementById('dashboard-tab1').classList.remove("tab-active");
            document.getElementById('dashboard-tab2').classList.remove("tab-active");
            activeContain.classList.remove("display-none");
            activeTab.classList.add("tab-active");
          }
          if (false) {
          }
        };
      </script>
      <div class="tab-row row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 dashboard-tab tab-active" id="dashboard-tab1" onclick="switchTab(event, 'my-catalogue', 'dashboard-tab1')">MY CATALOGUE</div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 dashboard-tab" id="dashboard-tab2" onclick="switchTab(event, 'my-watchlist','dashboard-tab2')">MY WATCHLIST</div>
      </div>
    </div>
  </dv>

</div>

<!-- TAB MY MOVIES AND WATCHLIST -->
<div class="bottom-section" id="bottom-section">
  <div class="container container-my-movies" id="my-catalogue">
    <%= render "my_film_index"%>
  </div>
  <div class="container container-my-movies display-none" id="my-watchlist">
    <%= render "my_watchlist_index"%>
  </div>
</div>




<!-- TAB EDIT PROFILE -->
<div class="col-sm-12">
 <div class="edit-profile">
 </div>
</div>

app/views/pages/landing.html.erb
<div class="landing-image row" style="background-image: url('<%= image_path "cinema.jpg" %>');">
<div class="col-md-6 col-lg-6 landing-content2">
</div>







<div class="landing-content col-xs-12 col-sm-12 col-md-6 col-lg-6">
  <div class="title">
    <h1>Feelin' Filmy</h1>
  </div>
  <div class="sub-title">
    <h2>Discover your next favorite movie</h2>
  </div>
  <div class="landing-button">
    <%= link_to  "Let's go!", movies_path, class: "landing-btn" %>
  </div>
</div>

app/views/pages/old_landing.html.erb
<!-- <div style="width:100%">
  <h3 style="text-align: center">BECAUSE BRIAN LIKED THESE FILMS, HE DISCOVERED...</h3>
</div>
<div>
  <ul class="liked flexbox">
    <li style="display:inline-block"><%= image_tag "#{@movie[1].poster}" %></li>
    <li style="display:inline-block"><%= image_tag "#{@movie[2].poster}" %></li>
    <li style="display:inline-block"><%= image_tag "#{@movie[3].poster}" %></li>
    <li style="display:inline-block"><%= image_tag "http://www.pngmart.com/files/3/Right-Arrow-PNG-Image.png" %></li>
    <li style="display:inline-block"><%= image_tag "#{@movie[5].poster}" %></li>
  </ul>
</div>
<ul class="bottom-third">
  <div class="flexbox">
      <li style="display:inline-block">
        <div style="border-top: 15px solid pink; border-bottom: 15px solid white; background-color: navy">
          <div class="avatar">
            <%= image_tag "#{@user.sample.avatar}" %>
          </div>
          <h3 style="text-align: center; color: white"><%= @user.sample.first_name %></h3>
          <h4 style="text-align:center; color:white">Characters</h4>
          <div>
            <%= image_tag "#{@movie.sample.poster}" %>
            <%= image_tag "#{@movie.sample.poster}" %>
          </div>
        </div>
      </li>
      <li style="display:inline-block">
        <div style="border-top: 15px solid pink; border-bottom: 15px solid white; background-color: navy">
          <div class="avatar">
            <%= image_tag "#{@user.sample.avatar}" %>
          </div>
          <h3 style="text-align: center; color: white"><%= @user.sample.first_name %></h3>
          <h4 style="text-align:center; color:white">Dialogue</h4>
          <div>
            <%= image_tag "#{@movie.sample.poster}" %>
            <%= image_tag "#{@movie.sample.poster}" %>
          </div>
        </div>
      </li>
      <li style="display:inline-block">
        <div style="border-top: 15px solid pink; border-bottom: 15px solid white; background-color: navy">
          <div class="avatar">
            <%= image_tag "#{@user.sample.avatar}" %>
          </div>
          <h3 style="text-align: center; color: white"><%= @user.sample.first_name %></h3>
          <h4 style="text-align:center; color:white">Acting</h4>
          <div>
            <%= image_tag "#{@movie.sample.poster}" %>
            <%= image_tag "#{@movie.sample.poster}" %>
          </div>
        </div>
      </li>
  </div>
</ul> -->

app/views/pages/watchlist.js.erb
document.getElementById("bottom-section").innerHTML = '<%= j render "my_watchlist_index"%>';

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-quotes">
   <h5>"<%= @quote["quote"] %>"  - <small><%= @quote["author"] %></small></h5>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <!-- New Navbar -->
<div class="navbar-wagon">
  <div>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>

      <%= image_tag url="https://res.cloudinary.com/chimeraggeddon/image/upload/v1528465150/favicon.png", height: 50 %>
    <% end %>
  </div>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar? %>
            <%= image_tag current_user.avatar, height: 300, width: 400, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <img src="https://vignette.wikia.nocookie.net/tumblr-survivor-athena/images/7/7a/Blank_Avatar.png/revision/latest/scale-to-width-down/477?cb=20161204161729" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to movies_path do %>
                <i class="fa fa-search"></i> <%= t(".search", default: "Search") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->

      <div class="sign-in-form"; style="padding-top: 20px">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name),
        wrapper: :inline_form, html: { class: "form-navbar form-inline"}) do |f| %>

            <%= f.input :email, required: false, autofocus: true, placeholder: "EMAIL", label: false %>





            <%= f.input :password, required: false, placeholder: "PASSWORD", label: false %>


            <%= f.button :submit, "Log in", :class => "btn-navbar"%>

        <% end %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn-sign-up btn-navbar btn-sign-up-navbar"  %>
      </div>
    <% end %>
  </div>
</div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "/pages/dashboard" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
          <% end %>
        </li>
        <li>
          <%= link_to "/movies/index" do %>
            <i class="fa fa-search"></i> <%= t(".search", default: "Search") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>